### ISSUE TITLE
error compiling with IDE 1.6

### ISSUE THREAD

**Issue by snelweg** [brunialti/MENWIZ#10]
Trying to compile quick_tour, using the in the zip file supplied libraries (button and LiquidCrystal).

`/Users/xx/Documents/Arduino/libraries/LiquidCrystal_I2C/FastIO.cpp: In function 'void fio_shiftOut1(fio_register, fio_bit, uint8_t, boolean)':
/Users/xx/Documents/Arduino/libraries/LiquidCrystal_I2C/FastIO.cpp:214:19: error: '_BV' was not declared in this scope
   if(value & _BV(i))`

**Comment by snelweg** [comment]
And this is what happens when I do a rebuild of everything:

`Build-opties gewijzigd, alles wordt opnieuw gebuild
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp: In member function 'void menwiz::drawMenu(_menu*)':
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:29:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define TSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s); b[strlen(b)]=' ';itoa(cur_menu->cur_item+1,tmp,10);strcat(tmp,"/");itoa(cur_menu->idx_o,tmp+strlen(tmp),10);b[col-strlen(tmp)-1]=126;memcpy(b+(col-strlen(tmp)),tmp,strlen(tmp));b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:376:5: note: in expansion of macro 'TSFORM'
     TSFORM(buf,mc->label,(int) col);
     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:29:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define TSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s); b[strlen(b)]=' ';itoa(cur_menu->cur_item+1,tmp,10);strcat(tmp,"/");itoa(cur_menu->idx_o,tmp+strlen(tmp),10);b[col-strlen(tmp)-1]=126;memcpy(b+(col-strlen(tmp)),tmp,strlen(tmp));b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:376:5: note: in expansion of macro 'TSFORM'
     TSFORM(buf,mc->label,(int) col);
     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:29:53: error: expected primary-expression before 'const'
 #define TSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s); b[strlen(b)]=' ';itoa(cur_menu->cur_item+1,tmp,10);strcat(tmp,"/");itoa(cur_menu->idx_o,tmp+strlen(tmp),10);b[col-strlen(tmp)-1]=126;memcpy(b+(col-strlen(tmp)),tmp,strlen(tmp));b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:376:5: note: in expansion of macro 'TSFORM'
     TSFORM(buf,mc->label,(int) col);
     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:29:53: error: expected ')' before 'const'
 #define TSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s); b[strlen(b)]=' ';itoa(cur_menu->cur_item+1,tmp,10);strcat(tmp,"/");itoa(cur_menu->idx_o,tmp+strlen(tmp),10);b[col-strlen(tmp)-1]=126;memcpy(b+(col-strlen(tmp)),tmp,strlen(tmp));b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:376:5: note: in expansion of macro 'TSFORM'
     TSFORM(buf,mc->label,(int) col);
     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:379:5: note: in expansion of macro 'FSFORM'
     FSFORM(buf,mc->label,(int) col);
     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:379:5: note: in expansion of macro 'FSFORM'
     FSFORM(buf,mc->label,(int) col);
     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected primary-expression before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:379:5: note: in expansion of macro 'FSFORM'
     FSFORM(buf,mc->label,(int) col);
     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected ')' before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:379:5: note: in expansion of macro 'FSFORM'
     FSFORM(buf,mc->label,(int) col);
     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:403:28: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
    strcpy_P(&buf[1],(const prog_char*)mn->label);
                            ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:403:28: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:403:22: error: expected primary-expression before 'const'
    strcpy_P(&buf[1],(const prog_char*)mn->label);
                      ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:403:22: error: expected ')' before 'const'
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:445:6: note: in expansion of macro 'FSFORM'
      FSFORM(buf,m[op->sbm].label,(int) col-1);
      ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:445:6: note: in expansion of macro 'FSFORM'
      FSFORM(buf,m[op->sbm].label,(int) col-1);
      ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected primary-expression before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:445:6: note: in expansion of macro 'FSFORM'
      FSFORM(buf,m[op->sbm].label,(int) col-1);
      ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected ')' before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:445:6: note: in expansion of macro 'FSFORM'
      FSFORM(buf,m[op->sbm].label,(int) col-1);
      ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:452:4: note: in expansion of macro 'FSFORM'
    FSFORM(buf,m[op->sbm].label,(int) col-1);
    ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:452:4: note: in expansion of macro 'FSFORM'
    FSFORM(buf,m[op->sbm].label,(int) col-1);
    ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected primary-expression before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:452:4: note: in expansion of macro 'FSFORM'
    FSFORM(buf,m[op->sbm].label,(int) col-1);
    ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected ')' before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:452:4: note: in expansion of macro 'FSFORM'
    FSFORM(buf,m[op->sbm].label,(int) col-1);
    ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp: In member function 'void menwiz::drawVar(_menu*)':
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:496:19: note: in expansion of macro 'FSFORM'
                   FSFORM(buf,op->label,(int) col-1);
                   ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:496:19: note: in expansion of macro 'FSFORM'
                   FSFORM(buf,op->label,(int) col-1);
                   ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected primary-expression before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:496:19: note: in expansion of macro 'FSFORM'
                   FSFORM(buf,op->label,(int) col-1);
                   ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected ')' before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:496:19: note: in expansion of macro 'FSFORM'
                   FSFORM(buf,op->label,(int) col-1);
                   ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp: In member function 'void menwiz::drawList(_menu*, int)':
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:567:3: note: in expansion of macro 'FSFORM'
   FSFORM(buf,((_option*)mc->o[i])->label,(int)cw-1);
   ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:59: error: ISO C++ forbids declaration of 'type name' with no type [-fpermissive]
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                           ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:567:3: note: in expansion of macro 'FSFORM'
   FSFORM(buf,((_option*)mc->o[i])->label,(int)cw-1);
   ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected primary-expression before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:567:3: note: in expansion of macro 'FSFORM'
   FSFORM(buf,((_option*)mc->o[i])->label,(int)cw-1);
   ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:30:53: error: expected ')' before 'const'
 #define FSFORM(b,s,l)    memset(b,32,l);strcpy_P(b,(const prog_char*)s);b[strlen(b)]=' ';b[l]=NULL;lcd->print(b)
                                                     ^
/Users/xx/Documents/Arduino/libraries/MENWIZ/MENWIZ.cpp:567:3: note: in expansion of macro 'FSFORM'
   FSFORM(buf,((_option*)mc->o[i])->label,(int)cw-1);
   ^
Fout bij compileren.
`

**Comment by zevero** [comment]
Try https://github.com/brunialti/MENWIZ_1_3_2 or my fork on https://github.com/zevero/MENWIZ
Its the same with only minor changes on my side.

**Comment by snelweg** [comment]
@Zevero great,that works!
